version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: "eu-west-1"
  exported-variables:
    - IMAGE_TAG
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd "$CODEBUILD_SRC_DIR/app" && npm ci
  pre_build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/app" && npm run lint
      - cd "$CODEBUILD_SRC_DIR/app" && npm test
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/app" && npm run build
      - export IMAGE_TAG="$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest} | cut -c 1-7)-$(date +%Y%m%d%H%M%S)"
      - export IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}"
      - cd "$CODEBUILD_SRC_DIR/app" && docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${IMAGE_URI}
      - docker push ${IMAGE_URI}
      - printf '{"imageUri":"%s"}' "$IMAGE_URI" > "$CODEBUILD_SRC_DIR/app/imageDetail.json"
  post_build:
    commands:
      - echo "Image pushed to ${IMAGE_URI}"
      - sed -i "s|\${IMAGE_URI}|$IMAGE_URI|g" "$CODEBUILD_SRC_DIR/k8s/deployment.yaml"
artifacts:
  files:
    - app/imageDetail.json
    - k8s/*
    - buildspec-deploy.yml
