AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Fargate Cluster + Service + ECR Repo for Express TS App

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC where ECS will run.

  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 1

  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 2

Resources:
  # -----------------------------------------------------
  # 1) ECR Repository
  # -----------------------------------------------------
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: express-ts-ecs

  # -----------------------------------------------------
  # 2) ECS Cluster
  # -----------------------------------------------------
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: express-ts-cluster

  # -----------------------------------------------------
  # 3) ECS Task Execution Role
  # -----------------------------------------------------
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsTaskExecutionRoleExpressTS
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # -----------------------------------------------------
  # 4) ECS Task Definition
  # -----------------------------------------------------
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: express-ts-task
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: express
          Image: "nginx" # placeholder, updated by CodePipeline
          PortMappings:
            - ContainerPort: 8000
          Essential: true

  # -----------------------------------------------------
  # 5) Security Group for ECS
  # -----------------------------------------------------
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound traffic to Express
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0

  # -----------------------------------------------------
  # 6) ECS Fargate Service
  # -----------------------------------------------------
  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - ECSTaskDefinition
    Properties:
      ServiceName: express-ts-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2

Outputs:
  ECRRepoUrl:
    Description: The URL of the ECR Repository
    Value: !GetAtt ECRRepository.RepositoryUri

  ECSClusterName:
    Value: !Ref ECSCluster

  ECSServiceName:
    Value: !Ref ECSService

  TaskDefinitionArn:
    Value: !Ref ECSTaskDefinition
